# DesafioControleFluxo
This is part of a challenge from DIO. We are practicing flux control and exceptions with this exercise.

### Excample 1: In this case we can see the exception is working properly when the user type a number bigger than the second parameter.

![img](https://github.com/Ravelos/DesafioControleFluxo/assets/86490406/35ef567d-07c6-4152-9a2d-f6bb8e23b71e)

### Example 2: Here we can see the program working as expected.

![img1](https://github.com/Ravelos/DesafioControleFluxo/assets/86490406/51992015-4bc6-4ec2-ab9a-bfaee3e5f73c)


